server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: firstService
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/first-service/**
      - id: secondService
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/second-service/**